# This file is to check the rest apis created
# vs code extension 'rest-client' is used for this

POST http://localhost:9808/create-short-url HTTP/1.1
content-type: application/json

{
    "long_url": "https://www.guru3d.com/news-story/spotted-ryzen-threadripper-pro-3995wx-processor-with-8-channel-ddr4,2.html",
    "user_id" : "e0dba740-fc4b-4977-872c-d360239e6b10"
}